from __future__ import annotations

import ast
import difflib
import hashlib
import shutil
from pathlib import Path

from sentinelforge.domain import Finding, PatchBundle


class FastAPIBOLAPatcher:
    """Create an isolated minimal patch and a permanent authorization regression test."""

    def create_bundle(self, finding: Finding, source_root: Path, run_root: Path) -> PatchBundle:
        source_root = source_root.resolve()
        run_root = run_root.resolve()
        patched_root = run_root / "patched"
        if patched_root.exists():
            shutil.rmtree(patched_root)
        run_root.mkdir(parents=True, exist_ok=True)
        shutil.copytree(source_root, patched_root)

        relative_source = Path(finding.path)
        source_path = source_root / relative_source
        patched_path = patched_root / relative_source
        original = source_path.read_text(encoding="utf-8")
        patched = self._patch_source(original, finding)
        patched_path.write_text(patched, encoding="utf-8")

        regression_relative = Path("tests") / f"test_security_{finding.finding_id}.py"
        regression_path = patched_root / regression_relative
        regression_path.parent.mkdir(parents=True, exist_ok=True)
        regression_path.write_text(self._regression_test(finding), encoding="utf-8")

        diff = self._diff(
            finding,
            original,
            patched,
            regression_relative,
            regression_path.read_text(),
        )
        patch_file = run_root / "remediation.patch"
        patch_file.write_text(diff, encoding="utf-8")
        patch_sha256 = hashlib.sha256(diff.encode()).hexdigest()
        return PatchBundle(
            finding_id=finding.finding_id,
            source_root=source_root,
            patched_root=patched_root,
            patch_file=patch_file,
            regression_test=regression_path,
            changed_files=(relative_source.as_posix(), regression_relative.as_posix()),
            patch_sha256=patch_sha256,
        )

    @staticmethod
    def _patch_source(source: str, finding: Finding) -> str:
        tree = ast.parse(source)
        resource = str(finding.evidence["resource_variable"])
        identity = str(finding.evidence["identity_variable"])
        ownership_field = str(finding.evidence["ownership_field"])
        target_function: ast.FunctionDef | ast.AsyncFunctionDef | None = None
        for node in ast.walk(tree):
            is_target = (
                isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
                and node.name == finding.function
            )
            if is_target:
                target_function = node
                break
        if target_function is None:
            raise ValueError(f"Function {finding.function!r} no longer exists")

        return_node: ast.Return | None = None
        for node in ast.walk(target_function):
            if isinstance(node, ast.Return) and isinstance(node.value, ast.Name):
                if node.value.id == resource:
                    return_node = node
                    break
        if return_node is None:
            raise ValueError(f"Could not find a return of {resource!r}")

        lines = source.splitlines(keepends=True)
        index = return_node.lineno - 1
        indent = lines[index][: len(lines[index]) - len(lines[index].lstrip())]
        guard = (
            f"{indent}if {resource}.{ownership_field} != {identity}.{ownership_field}:\n"
            f'{indent}    raise HTTPException(status_code=404, detail="Not found")\n'
        )
        lines.insert(index, guard)
        return "".join(lines)

    @staticmethod
    def _regression_test(finding: Finding) -> str:
        path = finding.endpoint.replace("{" + str(finding.evidence["identifier"]) + "}", "1")
        method = finding.method.lower()
        return f'''"""Generated by SentinelForge from finding {finding.finding_id}."""

from fastapi.testclient import TestClient

from app.main import app


client = TestClient(app)


def test_{finding.finding_id}_cross_tenant_access_is_denied() -> None:
    response = client.{method}("{path}", headers={{"x-user-id": "tenant-b-user"}})
    assert response.status_code == 404


def test_{finding.finding_id}_same_tenant_access_still_works() -> None:
    response = client.{method}("{path}", headers={{"x-user-id": "tenant-a-user"}})
    assert response.status_code == 200
'''

    @staticmethod
    def _diff(
        finding: Finding,
        original: str,
        patched: str,
        regression_relative: Path,
        regression: str,
    ) -> str:
        source_diff = difflib.unified_diff(
            original.splitlines(keepends=True),
            patched.splitlines(keepends=True),
            fromfile=f"a/{finding.path}",
            tofile=f"b/{finding.path}",
        )
        test_diff = difflib.unified_diff(
            [],
            regression.splitlines(keepends=True),
            fromfile="/dev/null",
            tofile=f"b/{regression_relative.as_posix()}",
        )
        return "".join((*source_diff, *test_diff))
