from __future__ import annotations

import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class PullRequest:
    number: int
    url: str
    title: str
    branch: str
    body: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "number": self.number,
            "url": self.url,
            "title": self.title,
            "branch": self.branch,
            "body": self.body,
        }


class PRGenerator:
    """Generate GitHub pull requests with security fixes."""

    def __init__(self, *, github_token: str | None = None) -> None:
        self._token = github_token

    def create_fix_branch(
        self,
        repo_dir: Path,
        finding_id: str,
        branch_name: str | None = None,
    ) -> str:
        if branch_name is None:
            branch_name = f"sentinelforge/fix-{finding_id[:12]}"
        self._git(repo_dir, "checkout", "-b", branch_name)
        return branch_name

    def commit_patches(
        self,
        repo_dir: Path,
        patched_files: list[Path],
        finding_id: str,
        message: str | None = None,
    ) -> str:
        if message is None:
            message = (
                f"fix(security): {finding_id}\n\n"
                f"Automated security patch by SentinelForge.\n"
                f"Finding: {finding_id}\n"
                f"This fix was verified in an isolated workspace before commit."
            )
        for f in patched_files:
            self._git(repo_dir, "add", str(f))
        self._git(repo_dir, "commit", "-m", message)
        return self._git(repo_dir, "rev-parse", "HEAD")

    def push_branch(
        self,
        repo_dir: Path,
        branch_name: str,
        remote: str = "origin",
    ) -> None:
        self._git(repo_dir, "push", "-u", remote, branch_name)

    def create_pull_request(
        self,
        repo_dir: Path,
        *,
        title: str,
        body: str,
        base: str = "main",
        head: str,
    ) -> PullRequest | None:
        cmd = [
            "gh", "pr", "create",
            "--title", title,
            "--body", body,
            "--base", base,
            "--head", head,
        ]
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            cwd=str(repo_dir),
            timeout=30,
        )
        if result.returncode != 0:
            return None
        url = result.stdout.strip()
        pr_number = 0
        if "/pull/" in url:
            try:
                pr_number = int(url.split("/pull/")[-1].split("?")[0])
            except ValueError:
                pass
        return PullRequest(
            number=pr_number,
            url=url,
            title=title,
            branch=head,
            body=body,
        )

    def generate_pr_body(
        self,
        finding: dict[str, Any],
        *,
        patch_sha256: str = "",
        verification_passed: bool = False,
    ) -> str:
        severity = finding.get("severity", "unknown").upper()
        rule_id = finding.get("rule_id", "unknown")
        description = finding.get("description", "")
        endpoint = finding.get("endpoint", "")
        remediation = finding.get("remediation", "")
        lines = [
            "## Security Fix",
            "",
            f"**Severity:** {severity}",
            f"**Rule:** `{rule_id}`",
            f"**Endpoint:** `{endpoint}`",
            "",
            "### Description",
            description,
            "",
            "### Remediation",
            remediation,
            "",
        ]
        if patch_sha256:
            lines.extend([
                "### Patch Receipt",
                f"- SHA-256: `{patch_sha256}`",
                f"- Verified: {'Yes' if verification_passed else 'Pending'}",
                "",
            ])
        lines.extend([
            "---",
            "*Generated by [SentinelForge](https://github.com/sentinelforge) "
            "proof-carrying release gate.*",
        ])
        return "\n".join(lines)

    def generate_branch_name(self, finding: dict[str, Any]) -> str:
        rule_id = finding.get("rule_id", "fix").lower().replace("sf-py-", "").replace("-", "/")
        finding_id = finding.get("finding_id", "")[:8]
        return f"sentinelforge/{rule_id}/{finding_id}"

    def apply_patches(
        self,
        repo_dir: Path,
        patches: dict[str, str],
    ) -> list[Path]:
        committed: list[Path] = []
        for relative_path, content in patches.items():
            target = repo_dir / relative_path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
            committed.append(target)
        return committed

    @staticmethod
    def _git(repo_dir: Path, *args: str) -> str:
        result = subprocess.run(
            ["git", *args],
            capture_output=True,
            text=True,
            cwd=str(repo_dir),
            timeout=30,
        )
        if result.returncode != 0:
            raise RuntimeError(f"git {' '.join(args)} failed: {result.stderr}")
        return result.stdout.strip()
